spring:
  datasource:
    url: <<datasource_url>>
    username: <<datasource_username>>
    password: <<datasource_password>>

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        jdbc:
          time_zone: UTC
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: <<client_id>>
            clientSecret: <<client_secret>>
            redirectUri: "{baseUrl}/api/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: <<client_id>>
            clientSecret: <<client_secret>>
            redirectUri: "{baseUrl}/api/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email
  mail:
    host: smtp.gmail.com
    port: 587
    username: <<mail_username>>
    password: <<mail_password>>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080
  oauth2:
    authorizedRedirectUri: http://localhost:8080/
server:
  error:
    include-message: always
    include-binding-errors: always
